// SPDX-License-Identifier: GPL-3.0-or-later

// Nickel (libnickel) functions resolved at load time. See nickelfootnote.cc for the
// symbol names. Functions returning a class by value take a hidden result
// pointer first (sret); ARM C++ constructors return `this`. Arguments passed
// by const reference are declared as pointers.
//
// Target firmware: 4.45.23697 (Clara Colour). Everything is checked when the
// plugin loads; the hooks that use a missing symbol stay off.

#ifndef NICKELFOOTNOTE_NICKEL_H
#define NICKELFOOTNOTE_NICKEL_H

#include <QVariantMap>

#include "version.h" // NFN_VERSION, generated by the Makefile

class QByteArray;
class QDialog;
class QLineEdit;
class QLocale;
class QObject;
class QString;
class QTextEdit;
class QWidget;

typedef void Volume; // opaque: Volume derives from Content at offset 0

// ReadingView (the open book)
extern Volume const *(*ReadingView_getVolume)(QWidget const *self); // returns a reference to a member
extern void (*ReadingView_getChapterTitle)(QString *sret, QWidget *self);
extern int  (*ReadingView_getCalculatedReadProgress)(QWidget *self);

// Content / Volume. The attribute keys are libnickel's QString constants; the
// pointers must not share their names (see the Makefile).
extern void (*Content_getDbValues)(QVariantMap *sret, Volume const *self);
extern void (*Content_getId)(QString *sret, Volume const *self);
extern QString const *Nickel_ATTRIBUTE_TITLE;
extern QString const *Nickel_ATTRIBUTE_ATTRIBUTION;
extern QString const *Nickel_ATTRIBUTE_SERIES;
extern QString const *Nickel_ATTRIBUTE_SERIES_NUMBER;

// Selection
extern void (*WebkitView_selectedText)(QString *sret, QWidget *self);
extern QWidget *(*SelectionMenuController_menuView)(QObject *self);
extern QWidget *(*SelectionMenuController_createMenuTextItem)(QObject *self, QWidget *parent, QString const *text);
extern void (*SelectionMenuView_addMenuItem)(QWidget *self, QWidget *item);

// Simple dialogs
extern QWidget *(*ConfirmationDialogFactory_showOKDialog)(QString const *title, QString const *text);

// Full-screen dialogs, the way NickelHardcover builds them: a content widget
// handed to N3DialogFactory::getDialog, pushed with MainWindowController.
extern QDialog *(*N3DialogFactory_getDialog)(QWidget *content, bool flag);
extern void (*N3Dialog_setTitle)(QDialog *self, QString const *title);
extern void (*N3Dialog_enableFullViewMode)(QDialog *self);
extern QWidget *(*N3Dialog_keyboardFrame)(QDialog *self);
extern void (*N3Dialog_showKeyboard)(QDialog *self);
extern void (*N3Dialog_hideKeyboard)(QDialog *self);
extern QObject *(*MainWindowController_sharedInstance)();
extern void (*MainWindowController_pushView)(QObject *self, QWidget *view);

// Keyboard. createKeyboard returns a SearchKeyboardController, which emits
// commitRequested() for the keyboard's Go key.
extern QObject *(*KeyboardFrame_createKeyboard)(QWidget *self, int keyboardScript, QLocale const *locale);
extern void (*SearchKeyboardController_setReceiver)(QObject *self, void *receiver, bool flag);
extern void (*SearchKeyboardController_setGoText)(QObject *self, QString const *text);
extern void *(*KeyboardReceiver_ctor_lineEdit)(void *self, QLineEdit *edit, bool flag);
extern void *(*KeyboardReceiver_ctor_textEdit)(void *self, QTextEdit *edit, bool flag);
static const int KeyboardReceiver_size = 0x24;

// Widgets (sizes from Nickel's own operator new calls)
extern QWidget *(*TouchLabel_ctor)(void *self, QWidget *parent, int flags);
static const int TouchLabel_size = 0x84;
extern QWidget *(*N3ButtonLabel_ctor)(void *self, QWidget *parent);
extern void (*N3ButtonLabel_setPrimaryButton)(QWidget *self, bool primary);
static const int N3ButtonLabel_size = 0x98;
extern QWidget *(*TouchTextEdit_ctor)(void *self, QWidget *parent);
extern void (*TouchTextEdit_setCustomPlaceholderText)(QWidget *self, QString const *text);
static const int TouchTextEdit_size = 0x38;
extern QLineEdit *(*TouchLineEdit_ctor)(void *self, QWidget *parent);
static const int TouchLineEdit_size = 0x40;

// Wi-Fi
extern QObject *(*WirelessWorkflowManager_sharedInstance)();
extern bool (*WirelessWorkflowManager_isInternetAccessible)(QObject *self);
extern void (*WirelessWorkflowManager_connectWireless)(QObject *self, bool a, bool b);
extern QObject *(*WirelessManager_sharedInstance)();

#endif
